config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  resources :cars do
    resources :rentals, only: [:new, :create]

  end
  put 'update', to: 'pages#update'
  get 'profile', to: 'pages#profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :rentals
  validates :name, presence: true
  validates :description, presence: true
  validates :year, presence: true, numericality: { only_integer: true, less_than: 2023, greater_than: 1900 }
  validates :model, presence: true
  # validates :image, presence: true
  validates :location, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?


  def unavailable?
    rentals.any? do |rental|
      rental.status
    end
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :car
  belongs_to :user
  # validates_uniqueness_of :car, scope: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rentals
  has_many :cars
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?

  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]


  def index
    # for searching for the year
    if params[:query].present? && params[:query].to_i != 0
      @cars = Car.where(year: params[:query])
    elsif params[:query].present?
      sql_query = "name ILIKE :query OR location ILIKE :query OR description ILIKE :query OR model ILIKE :query"
      @cars = Car.where(sql_query, query: "%#{params[:query]}%")
    else
      @cars = Car.all
    end
  end

  def show
    # @car = Car.find(params[:id])
    @rental = Rental.new
    @marker =
      {
        lat: @car.latitude,
        lng: @car.longitude
      }
  end

  def new
    @car = Car.new
    authorize @car
  end

  def edit
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    authorize @car

    if @car.save!
      redirect_to @car, notice: "Car was successfully created."
    else
      render :new
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy!
    respond_to do |format|
      format.html { redirect_to cars_path, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_car
    @car = Car.find(params[:id])
    authorize @car
  end

  def car_params
    params.require(:car).permit(:name, :description, :year, :model, :location, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
   render layout: 'home'
  end

  def about
  end

  def profile
    @user = current_user
  end

  def update
  rental_id = params[:request_id]
  @rental = Rental.find(rental_id)
  @rental.update_attribute(:status, true)
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
    before_action :set_list, only: [:new, :create]
  def new
    @rental = Rental.new
    authorize @rental
  end
  def create
    @rental = Rental.new(rental_params)
    @rental.car = @car
    authorize @rental
    if @rental.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end
  def destroy
    @rental = Rental.find(params[:id])
    @rental.destroy!
    redirect_to cars_path
  end

  private
  def set_list
    @car = Car.find(params[:car_id])
  end
  def rental_params
    params.require(:rental).permit(:status, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/edit.html.erb
<h1>Edit Page</h1>



<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<div class="car_container grid grid-cols-3 items-center gap-5">
  <% @cars.each do |car| %>
    <div class="car-card">
      <div>
        <h2 class="car_name"><%= car.name %> <%= car.model %></h2>
      </div>
      <%= cl_image_tag car&.photo&.key || "", height: 300, width: 400, crop: :fill %>
      <div class="px-6 pt-2 pb-2 mb-2 border-div">
        <%= link_to "View car", car_path(car),  class: "view_car" %>
      </div>
    </div>
  <% end %>
</div>
<%# if car.photo.attached? %>

app/views/cars/new.html.erb
<div class="car-wrapper">

 <div class="new-car-card">


<h1>Post a Car</h1>

  <%= simple_form_for(@car) do |f| %>
  <div class="form-inputs">
  <%=f.input :name %>
  <%=f.input :description %>
  <%=f.input :year %>
  <%=f.input :model %>
  <%=f.input :location %>
  <div class="photo-label"><%= f.input :photo, as: :file %></div>

  <%= f.submit class:"create-button" %>

  <% end %>
    </div>
<%= link_to 'Back', cars_path %>
</div>
</div>

app/views/cars/show.html.erb
<div class = "container mx-auto">
   <div class= "flex flex-row">
      <div class="basis-3/4">
         <div class="w-full">
            <h1 class="mb-2 text-center pb-12"><%= @car.name%> <%= @car.model%></h1>
         </div>
         <div>
            <%= cl_image_tag @car.photo.key, height: 300, width: 400, crop: :fill, class: "object-cover h-80 w-full card-image" %>
         </div>
         <div class="p-6 flex flex-col justify-start">
           <div class="text-wrapper">
            <p class="para-text mb-2">  <strong>Welcome!</strong>
              We hope you decide to take your next journey in this luxurious <%= @car.name%>!
            </p>
            <br>
            <p class="para-text mb-2"> <strong>Year: </strong><%= @car.year%></p>
            <div></div>
            <p class="para-text mb-2 pb-12"> <strong>Description: </strong><%= @car.description%></p>
            <br>

                <button type="button" >
                     <% if @car.unavailable? %>
                    <%= link_to 'Car unavailable', cars_path, class: "Rent-btn" %>
                    <% else %>
                      <%= simple_form_for [ @car, @rental ] do |b| %>
                        <%= b.association :user, :as => :hidden, label_method: :email, :input_html => { :value => current_user.id }  %>
                        <%= b.submit "Rent This Car", class:"Rent-btn" %>
                      <% end %>
                  <% end %>
                </button>
               </div>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>

            <div class="back-text">
            <%# <svg xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 512 512" width="30" height="30" ><path d="M360 224L272 224v-56c0-9.531-5.656-18.16-14.38-22C248.9 142.2 238.7 143.9 231.7 150.4l-96 88.75C130.8 243.7 128 250.1 128 256.8c.3125 7.781 2.875 13.25 7.844 17.75l96 87.25c7.031 6.406 17.19 8.031 25.88 4.188s14.28-12.44 14.28-21.94l-.002-56L360 288C373.3 288 384 277.3 384 264v-16C384 234.8 373.3 224 360 224zM256 0C114.6 0 0 114.6 0 256s114.6 256 256 256s256-114.6 256-256S397.4 0 256 0zM256 464c-114.7 0-208-93.31-208-208S141.3 48 256 48s208 93.31 208 208S370.7 464 256 464z" /></svg> %>
             <span><%= link_to 'Back', cars_path %></span>
            </div>
         </div>
      </div class= "text-inline">
      <div class="basis-1/4 p-5">
         <div class="row justify-content-center", id="map"
            data-marker="<%= @marker.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
         </div>
      </div>

   </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LuxCars</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.6.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.6.1/mapbox-gl.css' rel='stylesheet' />
  </head>
  <body>
    <%= render 'shared/navbar'  %>
    <main class="container mx-auto mt-28 flex">
    <p class="alert"><%= alert %></p>
    <%= yield %>

    </main>

    <%= render 'shared/footer'  %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LuxCars</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.6.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.6.1/mapbox-gl.css' rel='stylesheet' />
  </head>
  <body>
    <%= render 'shared/navbar'  %>
    <main class="flex h-100">
    <p class="alert"><%= alert %></p>
    <%= yield %>

    </main>

    <%= render 'shared/footer'  %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>

app/views/pages/home.html.erb
  <div class="home max-w-full h-200 w-100">
    <div class="flex justify-center">
      <div class="mb-3 xl:w-100">
        <div class="input-group relative flex flex-wrap items-stretch w-full mb-4">
        <%= form_tag cars_path, method: :get, class: "flex" do %>
         <%= text_field_tag :query,
          params[:query],
          class: "form-control relative flex-auto min-w-0 block w-full  px-3 py-4 text-base  font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
          placeholder: "city/car"
          %>
          <%= submit_tag "Search", class: "search-btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

 <%# FINISHED HOME %>

app/views/pages/profile.html.erb
<link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/styles/tailwind.css">
<link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css">
<main class="profile-page">
  <section class="relative block h-500-px">
    <%= image_tag "profile.page.jpeg", alt: "Profile Background", class: "absolute object-cover top-0 w-full h-full " %>
      <span id="blackOverlay" class="w-full h-full absolute opacity-50 bg-black"></span>
    </div>
    <div class="top-auto bottom-0 left-0 right-0 w-full absolute pointer-events-none overflow-hidden h-70-px" style="transform: translateZ(0px)">
      <svg class="absolute bottom-0 overflow-hidden" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" version="1.1" viewBox="0 0 2560 100" x="0" y="0">
        <polygon class="text-blueGray-200 fill-current" points="2560 0 2560 100 0 100"></polygon>
      </svg>
    </div>
  </section>
  <section class="relative py-16 bg-blueGray-200">
    <div class="container mx-auto px-4">
      <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg -mt-64">
        <div class="px-6">
          <div class="flex flex-wrap justify-center">
            <div class="w-full lg:w-3/12 px-4 lg:order-2 flex justify-center">
              <div class="relative">
                <%= image_tag "profile_pic.jpeg", alt: "", class: "shadow-xl rounded-full h-auto align-middle border-none absolute -m-16 -ml-20 lg:-ml-16 max-w-150-px" %>

                <%# <%= image_tag "movie-film.jpg", alt: "Le Wagon", class: "object-cover h-48 w-full card-image" %>
              </div>
            </div>
            <div class="w-full lg:w-4/12 px-4 lg:order-3 lg:text-right lg:self-center">
              <div class="py-6 px-3 mt-32 sm:mt-0">
                <h2 class="bg-yellow-600 active:bg-yellow-600 uppercase text-white font-bold hover:shadow-md shadow text-xs px-4 py-2 rounded outline-none focus:outline-none sm:mr-2 mb-1 ease-linear transition-all duration-150">
                  Rental confirmation
                </h2>
                <% @user.cars.each do |car| %>
                  <% car.rentals.each do |request| %>
                    <% car.rentals.each do |rental| %>
                      <% unless car.unavailable? %>
                        <%= request.user.email %>
                        <%= link_to 'Confirm', update_path(params: {request_id: request.id}), method: :put %>
                      <% else %>
                        <p><%=rental.user.email %></p>
                          <p> rental request has been approved</p>
                        <% end %>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="w-full lg:w-4/12 px-4 lg:order-1">
                <div class="flex justify-center py-4 lg:pt-4 pt-8">
                </div>
              </div>
            </div>
            <div class="text-center mt-12">
              <h3 class="text-4xl font-semibold leading-normal mb-2 text-blueGray-700 mb-2">
                <%= @user.name %>
              </h3>
              <%# <div class="text-sm leading-normal mt-0 mb-2 text-blueGray-400 font-bold uppercase">
              <i class="fas fa-map-marker-alt mr-2 text-lg text-blueGray-400"></i>
              Shanghai, China
            </div> %>
              <div class="mb-2 text-blueGray-600 mt-10">
                <i class="fas fa-briefcase mr-2 text-lg text-blueGray-400"></i><%= @user.email %>
              </div>
              <div class="mb-2 text-blueGray-600">
              </div>
            </div>
            <div class="mt-10 py-10 border-t border-blueGray-200 text-center">
              <div class="flex flex-wrap justify-center">
                <div class="w-full lg:w-9/12 px-4">
                  <p class="mb-4 text-lg leading-relaxed text-blueGray-700">
                    Welcome to Lux Cars your trusted service provider, we supply
                    you with the most luxurious and state of the range vechiles.
                    Quality service at great prices.
                  </p>
                </div>
              </div>
            </div>
            <div class="flex justify-around px-6">
            <div class="rounded-lg shadow-lg bg-white max-w-sm" >

                <%= image_tag "my rentals car pic.jpeg", alt: "", class: "rounded-t-lg" %>
                <div class="p-6">
                  <h5 class="text-gray-900 text-xl font-medium mb-2">My rentals</h5>
                    <% @user.rentals.where(status: true).each do |rental| %>
                      <%= rental.car.name %> <%= rental.car.model %>
                    <% end %>

                  <p class="text-gray-700 text-base mb-4">
                  </p>
                  <button type="button" class=" px-6 py-2.5 bg-yellow-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out">Show more</button>
                </div>
              </div>
              <div class="rounded-lg shadow-lg bg-white max-w-sm">
                <%= image_tag "my_cars_pic.jpeg", alt: "", class: "rounded-t-lg" %>
                <div class="p-6">
                  <h5 class="text-gray-900 text-xl font-medium mb-2">My cars</h5>
                  <p class="text-gray-700 text-base mb-4">
                  <% @user.cars.each do |car| %>
                  <%= car.name %>
                  <%= car.model %>
                  <% end %>
                  </p>
                  <button type="button" class=" px-6 py-2.5 bg-yellow-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out">Show more</button>
                </div>
              </div>


            </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
  <%# <h1>User: <%= @user.email %>
  <%# <h1>Rental Requests</h1> %>
  <%# <h1>My rentals</h1> %>
  <%# <% @user.rentals.where(status: true).each do |rental| %>
    <%# <%= rental.car.name %>
    <%# <% end %>

app/views/rentals/new.html.erb
<%= simple_form_for [ @car, @rental ] do |b| %>
  <%# <%= b.string :status %>
<<<<<<< HEAD
  <%= b.association :user %>
=======
  <%= b.association :user, :as => :hidden, label_method: :email, :input_html => { :value => current_user.id }  %>

>>>>>>> master
  <%# <% rental. %>
  <%= b.submit "Request to rental",  class: "btn btn-primary" %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="bg-black">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
      </div>
      <div class="flex-1 flex items-center sm:items-stretch sm:justify-start">
        <div class="flex-shrink-0 flex items-center">
          <%= image_tag "logo_lux_cars.png", alt: "Lux cars logo", class: "logo"%>
          <a href="#" class="logo-brand-text" >Lux Cars</a>
        </div>
      </div>
      <div class="inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <div class="hidden sm:block sm:ml-6">
          <div class=" inset-y-0 right-4 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <%= link_to "Cars",cars_path, class: "btn text-white font-bold  "%>
            <span>#</span>
            <%= link_to "Home",root_path, class: "btn text-white font-bold"%>
          </div>
        </div>
      </div>
      <!-- Profile dropdown -->
      <div class="ml-3 relative">
        <div>
          <button type="button" class="bg-gray-800 flex text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" id="dropdown" aria-expanded="false" aria-haspopup="true">
            <span class="sr-only">Open user menu</span>
            <img class="h-9 w-9 rounded-full center" src="https://images.unsplash.com/photo-1617646131875-0986960a4fb7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=327&q=80" alt="">
          </button>
        </div>
        <!--
            Dropdown menu, show/hide based on menu state.
          -->
        <div id="dropdown_links" class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
          <!-- Active: "bg-gray-100", Not Active: "" -->
            <% if user_signed_in? %>
              <%= link_to "Your Profile",profile_path, class: "block px-4 py-2 text-sm text-gray-700"%>
              <%= link_to "Post a Car",new_car_path, class: "block px-4 py-2 text-sm text-gray-700"%>
              <%= link_to "Sign Out",destroy_user_session_path, method: :delete, class: "block px-4 py-2 text-sm text-gray-700"%>
            <% else %>
              <%= link_to "Login",new_user_session_path,class: "block px-4 py-2 text-sm text-gray-700"%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</nav>